# Generated by Django 5.0.6 on 2024-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('halftime', 'Half Time')], default='fulltime', max_length=50),
        ),
    ]
