# Generated by Django 5.0.6 on 2024-07-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_details_linkedin_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photos/'),
        ),
    ]
