# Generated by Django 5.0.6 on 2024-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_details_linkedin_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='called_as',
            field=models.CharField(default='This is description', max_length=300, null=True),
        ),
    ]
