# Generated by Django 5.0.6 on 2024-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_details_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('halftime', 'Half Time')], default='Full Time', max_length=50),
        ),
    ]
