# Generated by Django 5.0.6 on 2024-07-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_job_details_skills_remove_user_details_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='applicants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('halftime', 'Half Time')], default='fulltime', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicants', to='base.job_details'),
        ),
    ]
