# Generated by Django 5.0.6 on 2024-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_job_details_applicants_alter_job_details_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
