# Generated by Django 5.0.6 on 2024-07-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_details_full_name_user_details_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_details',
            options={},
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='job',
        ),
    ]
