# Generated by Django 5.0.6 on 2024-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_details_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='self_des',
            field=models.TextField(default='This is description'),
        ),
    ]
