# Generated by Django 5.0.6 on 2024-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_details_self_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
