# Generated by Django 5.0.6 on 2024-07-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_details_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='linkedin_page',
            field=models.TextField(default='https://www.youtube.com/'),
        ),
    ]
