# Generated by Django 5.0.6 on 2024-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_details_called_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
