# Generated by Django 5.0.6 on 2024-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='full_name',
            field=models.CharField(default='abhiram', max_length=100),
        ),
    ]
