# Generated by Django 5.0.6 on 2024-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_user_details_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='resume',
            field=models.FileField(blank=True, default='resumes/default_resume.pdf', null=True, upload_to='resumes/'),
        ),
    ]
